### PR TITLE
[Feature] Turn Wintersky into a class

### LINKED ISSUE #4: [Feature] Allow rendering to multiple ThreeJS scenes
## Problem
bridge. has a split-screen mode that allows previewing two particle effects simultaneously. Currently, Wintersky doesn't support rendering emitters to two different ThreeJS scenes because the important `Wintersky.space` variable can only be set globally.
I tried switching the space variable out before starting the emitter but the `Emitter.tick()` function calls `Emitter.start()` internally so this breaks in `loop` mode too.

## Proposed Solution
There are two possible ways I could see this being solved:
1) Turn Wintersky into a class so users can create a new instance of the class containing all relevant state
```javascript
import { Wintersky, Emitter } from "wintersky"

const wintersky = new Wintersky({ space: myEmitterSpace })
// Creating an emitter...
const emitter = new Emitter(wintersky, config, options)
```

2) Allow passing a `space` property when creating a new Emitter
```javascript
new Wintersky.Emitter(config, { space: myEmitterSpace })
```

## Additional Notes
I can implement the solution you prefer if you see this as a suitable addition to Wintersky.

### PR DESCRIPTION
**Pull request by solvedDev**
## Motivation
- Closes #4 

## Breaking Changes
- Implementors must first create a new Wintersky `Scene` instance now: `const scene = new Wintersky.Scene({ fetchTexture: ... })`
- Global options are now set on the `Scene` instance: `scene.global_options.tick_rate = 30`
- Creating a new Emitter or Config now requires passing the Wintersky `Scene` context as the first constructor argument: `new Wintersky.Emitter(scene, ...)`

### CODE REVIEW

**Comment by JannisX11** [comment]
I would say it isn't necessary to initialize each particle with the Wintersky instance argument because it can easily be accessed via the emitter.

**Comment by solvedDev** [comment]
Will change that 👍

**Comment by solvedDev** [comment]
I've thought I should also mention that typing the library correctly is basically impossible with the new API now. TypeScript complains about accessing other classes over the `Wintersky` class and I don't think we can transition back to a namespace with the new API. I exported the `Emitter` and `Config` class individually inside of the types for now but that can be misleading because those actually only work for referring to types.

I believe it might be a good idea to re-evaluate the library export structure with a separate PR.

TypeScript Error

**Comment by solvedDev** [comment]
The alternative would be to add a new `Space` class to replace the `Wintersky` class & then reintroducing `Wintersky` as a pure namespace inside of this PR

**Comment by JannisX11** [comment]
I wonder how Vue 2 does this. They have a similar setup where the default export is both a constructor and namespace, and it works.

**Comment by solvedDev** [comment]
Good call, I'll take a look at it 👍

**Comment by solvedDev** [comment]
It doesn't seem like Vue adds any classes to the "Vue" object. It only adds "Vue.component(...)", "Vue.directive(...)" and similar methods. There might very well be a way to make the types work though but I am honestly no expert at writing raw TypeScript types. Nonetheless, I might give it another try tomorrow

**Comment by JannisX11** [comment]
Okay, I didn't realize there might be a difference between classes/constructors and other values.
In case this doesn't work out, let's make it a new class. I would call it `Scene`, since space is already used in several places for the actual 3D space that the particles move in.

**Comment by solvedDev** [comment]
PR is ready to merge from my side now 👍 
Types & the core library were tested inside of bridge. v2 and are fully working.

**Comment by JannisX11** [comment]
Nice, thanks!

**Pull request merged**
